LEARNERS_PAGE:
  - CAN_ADD_LEARNERS_TO_VOF
  - CAN_ADD_LEARNERS_FACILITOR_ASSISTANTS_TO_VOF
  - CAN_EDIT_LEARNERS_PROFILE
  - CAN_VIEW_LEARNERS_PROFILE
SURVEY:
  - CAN_VIEW_SURVEYS
  - CAN_EDIT_SURVEYS
  - CAN_DELETE_SURVEYS
  - CAN_RESPOND_TO_SURVEYS
  - CAN_VIEW_RESPONSES_TO_SURVEYS
  - CAN_SHARE_SURVEY_REPORTS
PITCH:
  - CAN_VIEW_PITCHES
  - CAN_CREATE_PITCHES
  - CAN_EDIT_PITCHES
  - CAN_DELETE_PITCHES
  - CAN_RATE_A_LEARNERS_PITCH
  - CAN_VIEW_LEARNERS_PITCH_RATINGS
SUBMISSIONS:
  - CAN_VIEW_SUBMISSIONS
  - CAN_SCORE_SUBMISSIONS
  - CAN_SUBMIT_SUBMISSIONS
  - CAN_EDIT_SUBMISSIONS
  - CAN_GRADE_SUBMISSIONS
CURRICULUM:
  - CAN_ARCHIVE_A_CIRRICULUM
  - CAN_VIEW_CIRRICULUMS
  - CAN_EDIT_CIRRICULUMS
PROGRAM:
  - CAN_CREATE_A_PROGRAM
  - CAN_VIEW_PROGRAM
  - CAN_EDIT_PROGRAM
  - CAN_DELETE_PROGRAM
SUPPORT:
  - CAN_VIEW_SUPPORT
LEARNING_ECOSYSTEM:
  - CAN_VIEW_LEARNING_ECOSYSTEMS
  - CAN_VIEW_EDIT_LEARNER_PROFILES
ANALYTICS:
  - CAN_VIEW_ANALYTICS
  - CAN_EXPORT_ANALYTICS
